### ISSUE TITLE
Question please?

### ISSUE THREAD

**Issue by eliezercazarestravelport** [dudleycarr/snappystream#107]
I have a requirement that reads as follow:

    /**
     * All streams should start with the "Stream identifier", containing chunk
     * type 0xff, a length field of 0x6, and 'sNaPpY' in ASCII.
     */

This is how DEV team is saving Json Objects in a Redis DB using Snappy Compression, my question is, how can I add the same Stream Identifier with this library? Thank you so much

**Comment by dudleycarr** [comment]
Have you tried the examples in the README? That resulting buffer from `SnappyStream` will start with the stream identifier.

**Comment by eliezercazares** [comment]
Hi Dudley, 
Your library is awesome! I did run the JEST tests and modified the tests a bit and it worked fine!!! :D
Now I am integrating your library to my project. 

Even though the comment above comes from the Snappy library's FramingFormat class, replicating it was too much of a challenge for me.

Thanks for sharing!

**Comment by dudleycarr** [comment]
Glad to hear it.
