### ISSUE TITLE
Compatibility with nodejs 6

### ISSUE THREAD

**Issue by vitali-ausianik** [dudleycarr/snappystream#6]
Hello Guys,
Could you please update "require" property of package.json to use the latest version of sse4_crc32 version? Current one isn't compatible with nodejs v6, "npm install" fails with 

```
npm ERR! sse4_crc32@4.1.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
```

I asked maintainers of sse4_crc32 repo and they tell that it works fine for them. So i believe it is old version issue.

**Comment by dudleycarr** [comment]
Fixed by #8
