### ISSUE TITLE
Use Buffer#readUIntLE instead of external dep

### ISSUE THREAD

**Issue by reviewher** [dudleycarr/snappystream#70]
[`Buffer#readUIntLE` has been available since v0.11.15 (many years before node v12)](https://nodejs.org/dist/latest-v16.x/docs/api/buffer.html#bufreaduintleoffset-bytelength) so using the native function will not decrease support surface.

[Under the hood it uses an internal `readUInt24LE` implementation.](https://github.com/nodejs/node/blob/master/lib/internal/buffer.js#L175).

**Comment by dudleycarr** [comment]
Fixed!
